### ISSUE TITLE
apache-stanbol 0.12 (release) BUILD FAILURE: integration-tests failed 

### ISSUE THREAD

**Issue by armeljanz** [zaizi/apache-stanbol-client#8]
Hi,

I am trying to install apache-stanbol 0.12 which contain contenthub
I have used :
1- http://www.apache.org/dyn/closer.cgi/stanbol/apache-stanbol-0.12.0-source-release.zip
2- https://apache.googlesource.com/stanbol/+archive/c9dcc29420802242f64ca7fdb9a786546f69d48d.tar.gz 
3- https://svn.apache.org/repos/asf/stanbol/branches/release-0.12/ (using svn co ...) after readind this issue https://github.com/zaizi/apache-stanbol-client/issues/3

For each tentative, i always delete the .m2 directory before starting the installation

For all the three tentatives, i always get the same error at the end: [ERROR] Failed to execute goal on project org.apache.stanbol.integration-tests: Could not resolve dependencies for project org.apache.stanbol:org.apache.stanbol.integration-tests:jar:0.12.1-SNAPSHOT (or 0.12.0): Failure to find org.apache.stanbol:org.apache.stanbol.launchers.full:jar:0.12.1-SNAPSHOT in http://repository.apache.org/snapshots

I don't find the jarfile in the .m2 directory nor in the stanbol directory  org.apache.stanbol.launchers.full-0.12.1-SNAPSHOT.jar (0.12.0.jar)

I think the error which cause integration-tests failed is the following:
[INFO] --- maven-antrun-plugin:1.6:run (default-cli) @ org.apache.stanbol.launchers.full ---
[INFO] Executing tasks

main:
     [java] Error: Unable to access jarfile stanbol\launchers\full\target\org.apache.stanbol.launchers.full-0.12.1-SNAPSHOT.jar
     [java] Java Result: 1

Here is the Stacktrace from the maven build process.

Kind regards,
Armel

[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Stanbol Launchers Full Launcher 0.12.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:1.6:run (default-cli) @ org.apache.stanbol.launchers.full ---
[INFO] Executing tasks

main:
     [java] Error: Unable to access jarfile stanbol\launchers\full\target\org.apache.stanbol.launchers.full-0.12.1-SNAPSHOT.jar
     [java] Java Result: 1
[INFO] Executed tasks
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Stanbol Launchers Full Launcher as WAR 0.12.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:1.6:run (default-cli) @ org.apache.stanbol.launchers.full-war ---
[INFO] No ant target defined - SKIPPED
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Stanbol Launchers Stable Launcher 0.12.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:1.6:run (default-cli) @ org.apache.stanbol.launchers.stable ---
[INFO] No ant target defined - SKIPPED
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Stanbol Statefull Webmodule Archetype 0.12.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:1.6:run (default-cli) @ statefull-webmodule-archetype ---
[INFO] No ant target defined - SKIPPED
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Stanbol Stateles Webmodule Archetype 0.12.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:1.6:run (default-cli) @ stateless-webmodule-archetype ---
[INFO] No ant target defined - SKIPPED
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Stanbol Enhancer Engine Archetype 0.12.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:1.6:run (default-cli) @ enhancer-engine-archetype ---
[INFO] No ant target defined - SKIPPED
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Stanbol Integration Tests 0.12.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Marmotta Kiwi Repository Service ................... SUCCESS [  0.862 s]
[INFO] Apache Stanbol Commons Tika Bundle ................. SUCCESS [  1.752 s]
[INFO] Apache Stanbol Commons Jobs API .................... SUCCESS [  0.062 s]
[INFO] Apache Stanbol Commons Jobs Web .................... SUCCESS [  0.622 s]
[INFO] Apache Stanbol Commons Jobs Reactor ................ SUCCESS [  0.127 s]
[INFO] Apache Stanbol Commons OpenNLP Utilities and Models  SUCCESS [  0.376 s]
[INFO] Apache Stanbol Commons OWL Bundle .................. SUCCESS [  1.604 s]
[INFO] Apache Stanbol Commons Indexed Clerezza inMemory graph implementation SUCCESS [  0.038 s]
[INFO] Apache Stanbol Commons JSON-LD API ................. SUCCESS [  0.019 s]
[INFO] Apache Stanbol Commons Launchpad ................... SUCCESS [  0.080 s]
[INFO] Apache Stanbol Commons Security Core ............... SUCCESS [  0.410 s]
[INFO] Apache Stanbol Commons Basic Authenticator ......... SUCCESS [  0.125 s]
[INFO] Apache Stanbol Commons Felix Webconsole Security Provider SUCCESS [  0.083 s]
[INFO] Apache Stanbol Commons User Management ............. SUCCESS [  0.352 s]
[INFO] Apache Stanbol Commons CAS Light ................... SUCCESS [  0.223 s]
[INFO] Apache Stanbol Commons Testing Jar Executor ........ SUCCESS [  0.017 s]
[INFO] Apache Stanbol Commons Testing HTTP Testing Library  SUCCESS [  0.029 s]
[INFO] Apache Stanbol Commons Testing Stanbol Utilities ... SUCCESS [  0.146 s]
[INFO] Apache Stanbol Commons ............................. SUCCESS [  0.010 s]
[INFO] Apache Stanbol Entityhub ........................... SUCCESS [  0.010 s]
[INFO] Apache Stanbol Entityhub Generic Service API ....... SUCCESS [  0.019 s]
[INFO] Apache Stanbol Entityhub Generic Test Framework .... SUCCESS [  0.269 s]
[INFO] Apache Stanbol Entityhub Generic Core .............. SUCCESS [  0.317 s]
[INFO] Apache Stanbol Entityhub Model Clerezza ............ SUCCESS [  0.096 s]
[INFO] Apache Stanbol Entityhub Model Sesame .............. SUCCESS [  0.084 s]
[INFO] Apache Stanbol Entityhub Query SPARQL .............. SUCCESS [  0.203 s]
[INFO] Apache Stanbol Entityhub Query SPARQL .............. SUCCESS [  0.292 s]
[INFO] Apache Stanbol Entityhub Site Linked Data Protocol . SUCCESS [  0.180 s]
[INFO] Apache Stanbol Entityhub Managed Site .............. SUCCESS [  0.032 s]
[INFO] Apache Stanbol Entityhub Yard based on Clerezza .... SUCCESS [  0.161 s]
[INFO] Apache Stanbol Entityhub Yard based on Solr ........ SUCCESS [  1.070 s]
[INFO] Apache Stanbol Entityhub Yard based on Sesame Sail . SUCCESS [  0.295 s]
[INFO] Apache Stanbol Entityhub LDPath Support ............ SUCCESS [  0.431 s]
[INFO] Apache Stanbol Entityhub Web Jersey HTTP Endpoint .. SUCCESS [  0.414 s]
[INFO] Apache Stanbol Entityhub Indexing .................. SUCCESS [  0.010 s]
[INFO] Apache Stanbol Entityhub Indexing Core ............. SUCCESS [  0.243 s]
[INFO] Apache Stanbol Entityhub Indexing Source for Jena TDB SUCCESS [  0.362 s]
[INFO] Apache Stanbol Entityhub Indexing Source for vCard . SUCCESS [  0.398 s]
[INFO] Apache Stanbol Entityhub Indexing Destination SolrYard SUCCESS [  0.320 s]
[INFO] Apache Stanbol Entityhub Indexing Generic RDF ...... SUCCESS [  0.465 s]
[INFO] Apache Stanbol Entityhub Indexing for geonames.org . SUCCESS [  0.205 s]
[INFO] Apache Stanbol Entityhub Indexing for DBpedia.org .. SUCCESS [  0.474 s]
[INFO] Apache Stanbol Entityhub Indexing for dblp ......... SUCCESS [  0.254 s]
[INFO] Apache Stanbol Entityhub Indexing for freebase.com . SUCCESS [  0.461 s]
[INFO] Apache Stanbol Entityhub Default Configuration ..... SUCCESS [  0.009 s]
[INFO] Apache Stanbol Ontology Manager : Services API ..... SUCCESS [  0.418 s]
[INFO] Apache Stanbol Ontology Manager : Input Sources (Clerezza-based) SUCCESS [  0.254 s]
[INFO] Apache Stanbol Ontology Manager : Input Sources (OWL API-based) SUCCESS [  0.106 s]
[INFO] Apache Stanbol Ontology Manager : Core ............. SUCCESS [  0.195 s]
[INFO] Apache Stanbol Ontology Manager : Network Multiplexer (Clerezza implementation) SUCCESS [  0.279 s]
[INFO] Apache Stanbol Ontology Manager : Registry Manager . SUCCESS [  0.185 s]
[INFO] Apache Stanbol Ontology Manager : Web .............. SUCCESS [  0.449 s]
[INFO] Apache Stanbol Ontology Manager Reactor ............ SUCCESS [  0.009 s]
[INFO] Apache Stanbol Rules Services API .................. SUCCESS [  0.098 s]
[INFO] Apache Stanbol Rules Manager ....................... SUCCESS [  0.264 s]
[INFO] Apache Stanbol Rules Abstract Adapter .............. SUCCESS [  0.196 s]
[INFO] Apache Stanbol Rules Jena Adapter .................. SUCCESS [  0.292 s]
[INFO] Apache Stanbol Rules SPARQL Adapter ................ SUCCESS [  0.130 s]
[INFO] Apache Stanbol Rules Clerezza Adapter .............. SUCCESS [  0.146 s]
[INFO] Apache Stanbol Rules SWRL Adapter .................. SUCCESS [  0.123 s]
[INFO] Apache Stanbol Rules Adapter Reactor ............... SUCCESS [  0.010 s]
[INFO] Apache Stanbol Rules Refactorer .................... SUCCESS [  0.264 s]
[INFO] Apache Stanbol Rules Web ........................... SUCCESS [  0.195 s]
[INFO] Apache Stanbol Rules Reactor ....................... SUCCESS [  0.010 s]
[INFO] Apache Stanbol Enhancer ............................ SUCCESS [  0.009 s]
[INFO] Apache Stanbol Enhancer Services API ............... SUCCESS [  0.038 s]
[INFO] Apache Stanbol Enhancer Core ....................... SUCCESS [  0.178 s]
[INFO] Apache Stanbol Enhancer Test framework ............. SUCCESS [  0.127 s]
[INFO] Apache Stanbol Enhancer RDF entities ............... SUCCESS [  0.105 s]
[INFO] Apache Stanbol Enhancer NLP ........................ SUCCESS [  0.062 s]
[INFO] Apache Stanbol Enhancer NLP JSON serialization support SUCCESS [  0.162 s]
[INFO] Apache Stanbol Enhancer Weighted Job Manager ....... SUCCESS [  0.188 s]
[INFO] Apache Stanbol Enhancer Event Jobmanager ........... SUCCESS [  0.037 s]
[INFO] Apache Stanbol Enhancer JobManager Reactor ......... SUCCESS [  0.011 s]
[INFO] Apache Stanbol Enhancer Chain: DefaultChain ........ SUCCESS [  0.040 s]
[INFO] Apache Stanbol Enhancer Chain: GraphChain .......... SUCCESS [  0.087 s]
[INFO] Apache Stanbol Enhancer Chain: Weighted ............ SUCCESS [  0.046 s]
[INFO] Apache Stanbol Enhancer Chain: List ................ SUCCESS [  0.047 s]
[INFO] Apache Stanbol Enhancer Web (Jersey) ............... SUCCESS [  0.206 s]
[INFO] Apache Stanbol Enhancer LDPath ..................... SUCCESS [  0.139 s]
[INFO] Apache Stanbol Enhancer Benchmark .................. SUCCESS [  0.102 s]
[INFO] Apache Stanbol Enhancer Defaults Configuration ..... SUCCESS [  0.010 s]
[INFO] Apache Stanbol Contenthub .......................... SUCCESS [  0.010 s]
[INFO] Apache Stanbol Contenthub Service API .............. SUCCESS [  0.069 s]
[INFO] Apache Stanbol Contenthub Solr Store ............... SUCCESS [  0.352 s]
[INFO] Apache Stanbol Contenthub Clerezza Store ........... SUCCESS [  1.242 s]
[INFO] Apache Stanbol Contenthub InMemory Store ........... SUCCESS [  0.117 s]
[INFO] Apache Stanbol Contenthub Store Reactor ............ SUCCESS [  0.010 s]
[INFO] Apache Stanbol Contenthub Search Solr Searcher ..... SUCCESS [  0.317 s]
[INFO] Apache Stanbol Contenthub Search Related Keyword Searcher SUCCESS [  0.436 s]
[INFO] Apache Stanbol Contenthub Featured Search .......... SUCCESS [  0.144 s]
[INFO] Apache Stanbol Contenthub Search Reactor ........... SUCCESS [  0.011 s]
[INFO] Apache Stanbol Contenthub Web ...................... SUCCESS [  1.416 s]
[INFO] Apache Stanbol Contenthub Clerezza LDPath Backend .. SUCCESS [  0.297 s]
[INFO] Apache Stanbol Enhancement Engines ................. SUCCESS [  0.009 s]
[INFO] Apache Stanbol Enhancement Engine : Tika ........... SUCCESS [  0.175 s]
[INFO] Apache Stanbol Enhancement Engine : HTML Extractor . SUCCESS [  0.171 s]
[INFO] Apache Stanbol Enhancement Engine : XMP Extractor .. SUCCESS [  0.082 s]
[INFO] Apache Stanbol Enhancement Engine : Refactor Engine  SUCCESS [  0.256 s]
[INFO] Apache Stanbol Enhancement Engine : Language Detection SUCCESS [  0.350 s]
[INFO] Apache Stanbol Enhancement Engine : Language Identifier SUCCESS [  0.042 s]
[INFO] Apache Stanbol Enhancement Engine : OpenNLP ........ SUCCESS [  0.010 s]
[INFO] Apache Stanbol Enhancement Engine : OpenNLP Sentence Detection SUCCESS [  0.130 s]
[INFO] Apache Stanbol Enhancement Engine : OpenNLP Tokenizer SUCCESS [  0.049 s]
[INFO] Apache Stanbol Enhancement Engine : OpenNLP POS Tagging SUCCESS [  0.045 s]
[INFO] Apache Stanbol Enhancement Engine : OpenNLP NER .... SUCCESS [  0.075 s]
[INFO] Apache Stanbol Enhancement Engine : OpenNLP Chunker  SUCCESS [  0.045 s]
[INFO] Apache Stanbol Enhancement Engine : POS tag based Chunker SUCCESS [  0.034 s]
[INFO] Apache Stanbol Enhancement Engine : Smart Chinese Tokenizer SUCCESS [  0.292 s]
[INFO] Apache Stanbol Enhancement Engine : NLP to RDF converter SUCCESS [  0.130 s]
[INFO] Apache Stanbol Enhancement Engine : Kuromoji NLP ... SUCCESS [  0.135 s]
[INFO] Apache Stanbol Enhancement Engine : RESTful NLP processing SUCCESS [  0.132 s]
[INFO] Apache Stanbol Enhancement Engine : RESTful Language Identification SUCCESS [  0.042 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Linking . SUCCESS [  0.008 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Linking Engine SUCCESS [  0.058 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Linking LabelTokenizer : Lucene SUCCESS [  0.488 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Linking LabelTokenizer : OpenNLP SUCCESS [  0.058 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Linking LabelTokenizer : Smart Chinese SUCCESS [  0.199 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Linking LabelTokenizer : Kuromoji Japanese SUCCESS [  0.153 s]
[INFO] Apache Stanbol Enhancement Engine : Entityhub Linking SUCCESS [  0.110 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Tagging . SUCCESS [  0.338 s]
[INFO] Apache Stanbol Enhancement Engine : Lucene FST Entity Linking SUCCESS [  0.204 s]
[INFO] Apache Stanbol Enhancement Engine : Keyword Extraction SUCCESS [  0.077 s]
[INFO] Apache Stanbol Enhancement Engine : Topic Classification (API) SUCCESS [  0.028 s]
[INFO] Apache Stanbol Enhancement Engine : Topic Classification SUCCESS [  2.557 s]
[INFO] Apache Stanbol Enhancement Engine : Topic Classification : Web API SUCCESS [  0.310 s]
[INFO] Apache Stanbol Enhancement Engine : Sentiment Word Classifier SUCCESS [  0.058 s]
[INFO] Apache Stanbol Enhancement Engine : Sentiment Summarization SUCCESS [  0.044 s]
[INFO] Apache Stanbol Enhancer Enhancement Engine : Disambiguation using Solr MLT SUCCESS [  0.045 s]
[INFO] Apache Stanbol Enhancement Engine : UIMA ........... SUCCESS [  0.010 s]
[INFO] Apache Stanbol Enhancement Engine : UIMA Remote Client SUCCESS [  0.122 s]
[INFO] Apache Stanbol Enhancement Engine : UIMA To Triples  SUCCESS [  0.040 s]
[INFO] Apache Stanbol Enhancement Engine : UIMA Local Client SUCCESS [  0.498 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Dereference Core SUCCESS [  0.073 s]
[INFO] Apache Stanbol Enhancement Engine : Entityhub Dereference SUCCESS [  0.201 s]
[INFO] Apache Stanbol Enhancement Engine : TextAnnotation new Model Conterter SUCCESS [  0.064 s]
[INFO] Apache Stanbol Enhancement Engine : Entity Co-Mention SUCCESS [  0.051 s]
[INFO] Apache Stanbol Enhancement Engine : CELI Engine .... SUCCESS [  0.116 s]
[INFO] Apache Stanbol Enhancement Engine : DBPedia Spotlight SUCCESS [  0.045 s]
[INFO] Apache Stanbol Enhancement Engine : Geonames Linking SUCCESS [  0.041 s]
[INFO] Apache Stanbol Enhancement Engine : OpenCalais ..... SUCCESS [  0.063 s]
[INFO] Apache Stanbol Enhancement Engine : Zemanta ........ SUCCESS [  0.050 s]
[INFO] Apache Stanbol CMS Adapter Parent .................. SUCCESS [  0.010 s]
[INFO] Apache Stanbol CMS Adapter Service API ............. SUCCESS [  0.031 s]
[INFO] Apache Stanbol CMS Adapter Core .................... SUCCESS [  0.234 s]
[INFO] Apache Stanbol CMS Adapter JCR ..................... SUCCESS [  0.387 s]
[INFO] Apache Stanbol CMS Adapter CMIS Bundle ............. SUCCESS [  0.770 s]
[INFO] Apache Stanbol CMS Adapter Web ..................... SUCCESS [  0.127 s]
[INFO] Apache Stanbol CMS Adapter Reactor ................. SUCCESS [  0.009 s]
[INFO] Apache Stanbol Reasoners ........................... SUCCESS [  0.009 s]
[INFO] Apache Stanbol Reasoners Services API .............. SUCCESS [  0.024 s]
[INFO] Apache Stanbol Reasoners Service Manager ........... SUCCESS [  0.079 s]
[INFO] Apache Stanbol Reasoners OWL API ................... SUCCESS [  0.311 s]
[INFO] Apache Stanbol Reasoners Jena ...................... SUCCESS [  0.028 s]
[INFO] Apache Stanbol Reasoners Test Framework ............ SUCCESS [  0.219 s]
[INFO] Apache Stanbol Reasoners Web ....................... SUCCESS [  0.449 s]
[INFO] Apache Stanbol Demos Enhancer VIE UI ............... SUCCESS [  0.070 s]
[INFO] Apache Stanbol Bundlelists ......................... SUCCESS [  0.009 s]
[INFO] Apache Stanbol Bundlelist for the OSGi Framework ... SUCCESS [  1.127 s]
[INFO] Apache Stanbol Bundlelist for Commons Libraries .... SUCCESS [  3.896 s]
[INFO] Apache Stanbol Bundlelist for Default Data ......... SUCCESS [  0.064 s]
[INFO] Apache Stanbol Bundlelist for OpenNLP Models ....... SUCCESS [  0.272 s]
[INFO] Apache Stanbol Bundlelist for Sentiment Data ....... SUCCESS [  0.057 s]
[INFO] Apache Stanbol Bundlelist for Enhancer ............. SUCCESS [  1.692 s]
[INFO] Apache Stanbol Bundlelist for Entityhub ............ SUCCESS [  0.660 s]
[INFO] Apache Stanbol Bundlelist for CMS Adapter .......... SUCCESS [  0.558 s]
[INFO] Apache Stanbol Bundlelist for Contenthub ........... SUCCESS [  0.562 s]
[INFO] Apache Stanbol Bundlelist for Ontology Manager ..... SUCCESS [  0.455 s]
[INFO] Apache Stanbol Bundlelist for Reasoners ............ SUCCESS [  0.445 s]
[INFO] Apache Stanbol Bundlelist for Rules ................ SUCCESS [  0.510 s]
[INFO] Apache Stanbol Marmotta KiWi Repository Bundles .... SUCCESS [  1.809 s]
[INFO] Apache Stanbol Bundlelist for Security ............. SUCCESS [  0.369 s]
[INFO] Apache Stanbol Bundlelist for the Clerezza Shell ... SUCCESS [  0.955 s]
[INFO] Apache Stanbol Bundlelist for Language Support: Smart Chinese SUCCESS [  0.505 s]
[INFO] Apache Stanbol Bundlelist for Language Support: Kuromoji Japanese SUCCESS [  0.274 s]
[INFO] Apache Stanbol Launchers Full Launcher ............. SUCCESS [  3.174 s]
[INFO] Apache Stanbol Launchers Full Launcher as WAR ...... SUCCESS [  0.221 s]
[INFO] Apache Stanbol Launchers Stable Launcher ........... SUCCESS [  0.156 s]
[INFO] Apache Stanbol Statefull Webmodule Archetype ....... SUCCESS [  0.161 s]
[INFO] Apache Stanbol Stateles Webmodule Archetype ........ SUCCESS [  0.010 s]
[INFO] Apache Stanbol Enhancer Engine Archetype ........... SUCCESS [  0.014 s]
[INFO] Apache Stanbol Integration Tests ................... FAILURE [  0.312 s]
[INFO] Apache Stanbol Reactor ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2015-06-24T07:46:46+01:00
[INFO] Final Memory: 155M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.apache.stanbol.integration-tests: Could not resolve dependencies for project org.apache.stanbol:org.apache.stanbol.integration-tests:jar:0.12.1-SNAPSHOT:
Failure to find org.apache.stanbol:org.apache.stanbol.launchers.full:jar:0.12.1-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempte
d until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.apache.stanbol.integration-tests

**Comment by dileepajayakody** [comment]
Hi,
Are you still getting this error?
This build error is no longer there in http://svn.apache.org/repos/asf/stanbol/branches/release-0.12/.
Let me know if you get trouble building from the release branch

Thanks,
Dileepa

**Comment by armeljanz** [comment]
Hi Dileepa,

I finaly use this link to get a version of Stanbol that i use without any problem

http://www.salzburgresearch.at/~rwesten/stanbol/0.12.1/org.apache.stanbol.launchers.full-0.12.1-SNAPSHOT.jar
http://www.salzburgresearch.at/~rwesten/stanbol/0.12.0/org.apache.stanbol.launchers.full-0.12.0.jar

Thank Dileepa for your answer

Armel Nzekon

**Comment by sumantapakira** [comment]
Hi Dileepa,

I'm trying to build using http://svn.apache.org/repos/asf/stanbol/branches/release-0.12/
But every time its failing, What is the correct code base?
